## manipuler un tableau

In [15]:
import numpy as np
np.__version__

'1.26.3'

In [16]:
arr = np.array(range(12)).reshape(4, 3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [17]:
# élément
arr[2][2]
# ==
arr[2, 2]
# une ligne
arr[1]
# une colonne => sélection de lignes et ensuites de colonnes
arr[:,0]

## selection depuis la gauche vers la droite et inversement
arr[2:, 1:]
arr[-2:, 1:]

##
arr[::2, 1:]

array([[1, 2],
       [7, 8]])

In [18]:
# 1ère de mouture "asymétrique" de broadcasting
# on a une opération qui mélange des variables de dimensions différentes 
arr[::2, 1:] = 0
arr

array([[ 0,  0,  0],
       [ 3,  4,  5],
       [ 6,  0,  0],
       [ 9, 10, 11]])