#### transformer un tableau

In [2]:
import numpy as np
from time import time
rng = np.random.default_rng(seed=int(time()))
np.__version__

'1.26.3'

In [6]:
arr = rng.integers(
    0, 20, 
    size=16, 
    dtype=np.int8, 
    endpoint=True
).reshape(4, 4)
arr

array([[13, 14,  0, 19],
       [ 8, 17, 15, 13],
       [ 3, 15, 11,  6],
       [ 7,  2, 20, 11]], dtype=int8)

In [15]:
# broadcast matrice + vecteur (ligne)
arr + [1, 2, 3, 4]
arr + np.array([1, 2, 3, 4])
arr + np.array([1, 2, 3, 4]).reshape(1, 4)


array([[14, 16,  3, 23],
       [ 9, 19, 18, 17],
       [ 4, 17, 14, 10],
       [ 8,  4, 23, 15]])

In [16]:
# broadcast matrice + vecteur (colonne)
arr + np.array([1, 2, 3, 4]).reshape(4, 1)

array([[14, 15,  1, 20],
       [10, 19, 17, 15],
       [ 6, 18, 14,  9],
       [11,  6, 24, 15]])

In [17]:
# reshape (x, y) => (y, x) => transposition
row = np.array([1, 2, 3, 4]).reshape(1, 4)
col = row.T
row, col

(array([[1, 2, 3, 4]]),
 array([[1],
        [2],
        [3],
        [4]]))

In [20]:
# row.dot(col) => normal 1, 4 x 4, 1 => scalire
row @ col
# attention 4, 1 x 1, 4 => matrice 4, 4
col @ row

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])

In [21]:
# certaines opérations ont besoin de dimension analogues
[1, 2, 4] @ col

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)

In [24]:
## atention: pour broadcaster la variable 
## doit avoir des dimensions analogues a la variable de départ
arr + np.ones((4,2))

ValueError: operands could not be broadcast together with shapes (4,4) (4,2) 

In [25]:
# application linéaire
3 * arr + row

array([[40, 44,  3, 61],
       [25, 53, 48, 43],
       [10, 47, 36, 22],
       [22,  8, 63, 37]])

In [27]:
# vectorisation permet la lisibilité du code et 
# d'oublier la boucle for en python (moins performante)
np.around(np.cos(arr) + np.pi / 2, 2)

array([[2.48, 1.71, 2.57, 2.56],
       [1.42, 1.3 , 0.81, 2.48],
       [0.58, 0.81, 1.58, 2.53],
       [2.32, 1.15, 1.98, 1.58]], dtype=float16)

In [28]:
patients = np.array([[1.65, 64, 126, 76], [1.78, 95, 136, 85]])
patients

array([[  1.65,  64.  , 126.  ,  76.  ],
       [  1.78,  95.  , 136.  ,  85.  ]])

In [38]:
# aggrégats liés à toutes les données
# patients.mean(), patients.max(), patients.size 
np.mean(patients, axis=0)
# la moyenne est appliquée sur les objets lignes directement
(patients[0] + patients[1])/2

np.mean(patients, axis=1)
# la moyenne est appliquée à l'intérieur des lignes i.e les objets colonnes
np.array([patients[0].mean(), patients[1].mean()])
np.mean(patients.T, axis=0)

# ==> axis = 0 == LIGNE, axis =1 == COLONNES


array([66.9125, 79.445 ])

In [47]:
# example de l'imc donc je dois manipuler les attributs des lignes donc => les objets colones
# avec des lambda = avec l'axe 1 => le param de la fct est la ligne
np.apply_along_axis(lambda line : line[1]/(line[0]**2), arr=patients, axis=1)

array([23.50780533, 29.98358793])

In [49]:
# fonction custom sur les lignes
# avec des lambda = avec l'axe 0 => le param de la fct est la colonne
np.apply_along_axis(lambda c: np.average(c, weights=[0.75,1]), arr=patients, axis=0)
(0.75*patients[0] + patients[1])/1.75

array([  1.72428571,  81.71428571, 131.71428571,  81.14285714])

#### filtrer un tableau

In [50]:
arr = rng.integers(1, 100, size=20)
arr

array([ 4, 24, 84, 67, 17, 76, 47, 37, 94, 52, 10, 63, 18, 97, 45, 93, 21,
        2, 23, 67], dtype=int64)

In [60]:
cond_inf_50 = arr < 50
# transtypage en booléen
cond_odd = (arr % 2).astype(dtype=np.bool_)
# arr[cond_inf_50]
## opérateurs booléen en filtrage: &, |, ~ non
arr[(arr < 50) & (~cond_odd)]

array([ 4, 24, 10, 18,  2], dtype=int64)

In [59]:
(arr % 2).astype(dtype="bool")


array([False, False, False,  True,  True, False,  True,  True, False,
       False, False,  True, False,  True,  True,  True,  True, False,
        True,  True])

In [78]:
# unpacking
arr1, arr2 = [ rng.integers(1, 10, size=10) for _ in range(2) ]
print(arr1, arr2)
# Q: rendre le tableau des valeurs qui ne sont pas doublonné
print(np.unique(np.concatenate([arr1[~np.isin(arr1, arr2)], arr2[~np.isin(arr2, arr1)]])))


[6 7 5 9 7 6 5 2 4 5] [2 3 8 3 2 1 4 6 5 9]
[1 3 7 8]


array([7], dtype=int64)