### exercices

In [11]:
import numpy as np
from time import time
from scipy import stats
rng = np.random.default_rng(seed=int(time()))
np.__version__

'1.26.3'

In [5]:
# unpacking
arr1, arr2 = [ rng.integers(1, 10, size=10) for _ in range(2) ]
print(arr1, arr2)
# Q: rendre le tableau des valeurs qui ne sont pas doublonné
print(np.unique(np.concatenate([arr1[~np.isin(arr1, arr2)], arr2[~np.isin(arr2, arr1)]])))
# Q: données doublonnées => intersection
np.intersect1d(arr1, arr2)

[8 9 8 7 4 6 4 4 5 6] [6 6 5 6 4 6 8 5 6 7]
[9]


array([4, 5, 6, 7, 8], dtype=int64)

In [12]:

# calculer un taux moyen de retour d'une action
arr = np.array([1000, 1320, 1148, 855, 993])
# 1. trouver le tableau des taux d'accroissement (p(t+1) - p(t))/p(t) + 1 > 1 'si augmentation et < 1 pour baisse
rates = np.around(np.diff(arr)/arr[:-1] + 1, 2)
# rates.mean() - 1
stats.gmean(rates) - 1
# arith: sigma(x)/nb_valeur
# géométrique : racine_nb_valeur(PI(x))

-0.0035724581330448535

In [16]:
# patients.txt
arr = np.genfromtxt(
    "patients.txt",
    delimiter=","
).reshape(3,4)
arr

array([[ 64.4, 173.8, 130. ,  80. ],
       [ 52.4, 163.8, 146. ,  90. ],
       [  nan, 184.2, 125. ,  79. ]])

In [24]:
# patients_reel.txt
arr = np.genfromtxt(
    "patients_reel.txt",
    # encoding="utf8",
    delimiter=",",
    comments="//",
    skip_header=1,
    missing_values="???",
    filling_values=0,
    usecols=(0,1,2,3),
    # dtype="f8,f8,i4,i4,U2"
)
arr

array([[ 64.4, 173.8, 130. ,  80. ],
       [ 52.4, 163.8, 146. ,  90. ],
       [  0. , 184.2, 125. ,  79. ]])